networks:
  grid-networks:
    driver: bridge
    name: monitoring-net

volumes:
  mosquitto_data:
  influxdb_data:
  grafana_data:


services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
    networks:
      - grid-networks
    restart: always

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG_NAME}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_NAME}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

    networks:
      - grid-networks
    restart: always

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - grid-networks
    restart: always

  transformer-simulation:
    image: hfs7/transformer-simulation:v1.0
    environment:
      - MQTT_BROKER=mosquitto
    networks:
      - grid-networks
    restart: always
    depends_on: 
      - mosquitto

  bridge-mqtt-influxdb:
    image: hfs7/mqtt_to_influxdb:latest
    environment:
      - MQTT_BROKER=mosquitto
      - INFLUX_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG_NAME=${INFLUXDB_ORG_NAME}
      - INFLUXDB_NAME=${INFLUXDB_NAME}
    networks:
      - grid-networks
    restart: always
    depends_on:
      - mosquitto
      - influxdb
